export { useClientsQuery } from './hooks/useClientsQuery'
export { useCreateClientMutation } from './hooks/useCreateClientMutation'
export { useClientSearchQuery } from './hooks/useClientSearchQuery'
export type { Client } from './types/client'
export { getClients, getClient, createClient, updateClient } from './api/clientApi'
